### ISSUE TITLE
Routing exceptions

### ISSUE THREAD

**Issue by bacloud14** [bacloud14/WeatherVenue#13]
Implement proper routing responses:

1. Validate and securely escape `/nearby/:city` parameters.
2. Proper response for `/*/` other non valid URLs. (as bad request 400 or 404 not found).
3. Escape Redis parameters.

Links:
https://express-validator.github.io/docs/check-api.html
https://nodesource.com/blog/nine-security-tips-to-keep-express-from-getting-pwned

**Comment by ME-ON1** [comment]
Are you working on this ??

**Comment by bacloud14** [comment]
I did validation of inputs only.

**Comment by ME-ON1** [comment]
OK done

**Comment by bacloud14** [comment]
We already worked on 404 by the way? I copied your addition in the last pull request and add some changes in the last commit.

**Comment by bacloud14** [comment]
This should be resolved no?

**Comment by ME-ON1** [comment]
Yeah!! if you are looking any non-listed route then they will be going straight to 404 page. 
but it can be done better , i guess, with more better error handling with 5xx and 4xx codes like mentioned by you!! 
> Proper response for /*/ other non valid URLs. (as bad request 400 or 404 not found).

**Comment by bacloud14** [comment]
yes I agree, I forgot about "status" you are right. anyway, you can claim this, or let go for now, not urgent.
