### ISSUE TITLE
Add licence file + mention in readme about it.

### ISSUE THREAD

**Issue by darnuria** [bacloud14/WeatherVenue#16]
Hi! Would suggest a good first issue: Add ISC licence to the project (file+readme mention) according to this line in `package.json` https://github.com/bacloud14/SunnySunday/blob/master/package.json#L12

Would send a clear signal to other contributor and user what are their right.

Thanks have a good day. :)

**Comment by bacloud14** [comment]
Shuut, I missed property licensing the "GitHub repository", although I was aware about the default nom license. 
Again shuut :) I need to revise licenses for something like "use,  modify, include same license, mention this one root license, no sublicensing" Which is not ISC nor MIT.

**Comment by bacloud14** [comment]
Thanks for pointing out 😃

**Comment by darnuria** [comment]
No problems. :D

**Comment by darnuria** [comment]
I love this website for getting an idea about licenses https://choosealicense.com/
