### ISSUE TITLE
Custom 404 response page

### ISSUE THREAD

**Issue by bacloud14** [bacloud14/WeatherVenue#20]
It should include header and footer and a message 404 resource not found.

**Comment by ME-ON1** [comment]
I can take this issue.

**Comment by bacloud14** [comment]
Thanks @ME-ON1 for showing interest 😁
Please include partials like in index page, because they are already implemented: head, navbar, footer,...

**Comment by ME-ON1** [comment]
```
$ npm start 

Error: connect ECONNREFUSED 127.0.0.1:8866
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8866
}

```
hey, i was setting up this project locally but was getting this error. Any idea about this??

**Comment by bacloud14** [comment]
kindly see this: https://github.com/bacloud14/WeatherVenue/blob/master/CONTRIBUTING.pdf

of course I'm using Redis, I don't expect it another thing. Check your `.env` file, you must create one with these:

```
NODE_ENV=dev
PORT=3000
REDIS_PORT=6379
HONEYPOT_KEY=####
OPENWEATHERMAP_API_KEY=####
GOOGLE_MAPS_API_KEY=####

```

let me know 💯

**Comment by bacloud14** [comment]
I run the project without running Redis server, I got the same error. so it is Redis server.

**Comment by bacloud14** [comment]
please `git fetch` then `git pull` since you are behind a big commit
