### ISSUE TITLE
Vertical scroll magnetic effect

### ISSUE THREAD

**Issue by bacloud14** [bacloud14/WeatherVenue#30]
Considered sections:

https://github.com/bacloud14/WeatherVenue/blob/6e01d66a95703593c368e861be1245d9c89b1e04/views/index.ejs#L30
https://github.com/bacloud14/WeatherVenue/blob/6e01d66a95703593c368e861be1245d9c89b1e04/views/index.ejs#L36
https://github.com/bacloud14/WeatherVenue/blob/6e01d66a95703593c368e861be1245d9c89b1e04/views/index.ejs#L44

**Comment by bacloud14** [comment]
it should stick only when one city is searched for. (otherwise the web page is empty)

**Comment by ME-ON1** [comment]
Isnt this will be hard when doing with pug!? 
Can we use jquery via CDN or something??

**Comment by bacloud14** [comment]
if I get you, JQuery is already there.

**Comment by ME-ON1** [comment]
Sorry not pug!? I meant ejs !!

**Comment by ME-ON1** [comment]
I can work on this issue btw if you're not working on this

**Comment by bacloud14** [comment]
I am not working on this. You are welcome, thanks !!!

**Comment by ME-ON1** [comment]
Nope sorry man i got involved into some other tasks.
