### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jordanfinners** [bacloud14/WeatherVenue#31]
Hey @bacloud14 
Here's your code review! Please let me know if this makes sense, or if there is anything you want more help/info on.

I would not include your keys in the repository, I know you are trying to help people out but it could lead to a large bill or abuse in some way.
I've also seen one is hardcoded in [here](https://github.com/bacloud14/WeatherVenue/blob/master/views/html_dependencies/weather-map-view.ejs)
What I would suggest is you could provide links to where people who want to use this could get the keys e.g. a link to google maps etc

The links to view the application aren't working for me, just fyi.
I would recommend looking into serverless application, like Firebase, Azure Functions, Vercel etc.
As you could then split the API and the website up. Which keeps things more focussed in each section and allows for better scalability.

I would remove the commented-out code and lines with /// 0 ////// as they distract from the code itself :)
It you ever need to switch back or look at it again, you can see it in the commit history.

Your `index.js` is pretty large, what I would suggest is changing this so this file only does routing and the logic for your endpoints moved out into other files. You could consider each file to be responsible for one thing, e.g. the index.js for setting up and routing (or you could actually move the routing out to a different file), one for caching, one for interacting with the weather/air pollution api etc.

I would suggest for third party apis like fetch weather into a separate file, or class for example
```js
class OpenWeather {
    constructor(key) {
        this.key = key
    }

    getWeather(city, language) {
        // make api call
    }

    getAirPollution(city, language) {
        //make api call
    }
}

const api = new OpenWeather('someKey')

api.getAirPollution(city, language)
```
Which would allow you to test it.

I would also look to add tests for this project.

When you have an if with a return in it, you don't need the else for example in index.js you can do this instead
```js
if (result) {
        return res.status(200).send({
          error: false,
          message: `Weather data for nearby cities for ${cityname} from the cache`,
          data: JSON.parse(result)
        })
}
        const query = {
          latitude: geometry.lat,
          longitude: geometry.lng
        }
```

Do you need cookies? I would look to see if you could use google analytics without cookies or a privacy focussed alternative.

You don't need to include your public (built UI) folder in your repository. It should be generated each time and so doesn't need to be committed.

I would look at some linting with `eslint` or `prettier` to help format your code.

I would also look at adding some CI (Continuous Integration) using Github Actions for example to run tests and lint on ever push

If you are mapping data you can use `.map` in javascript rather than `.forEach` which makes your code simpler.

For localisation, rather than providing separate HTML files, normally its preferred to load just the content via JSON, there are lots of libraries to help with this.

The use of redis is really cool for caching your content. if you change to use [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) in your website you can also use a cache here as well as in your api so you are then doing it frontend and back :)

**Comment by bacloud14** [comment]
This is very valuable, I appreciate your review so much !!
The list is long but everything is so clear, and I feel like agreeing on each point. I will move on with these suggestions as there is no time to let go, everything is neat. 
I probably have a question or two and will be back later or tomorrow.
thanks a lot !

**Comment by jordanfinners** [comment]
Great! Any questions just let me know 😊

**Comment by bacloud14** [comment]
I'm back :)
The list is long and keeping me motivated I already had some changes while I agree on everything except what I did not understand.

- The app is running, probably due to my bad habit of a lot of commits, it went off the time you tried. check this: https://www.weathervenue.com/ (you can check your city ⚡ )
- About serverless applications, i don't see necessarily the utility here ? what do your think? The app itself is a UI and a middlware to fetch weather data, no need for absolute UI/server separation right ? (knowing the burden of dependencies of firebase and stuff)
- The **class OpenWeather, the keys, index.js being large, routes suggestion and tests** are really great suggestions, I will definitely put these in practice.
- Cookies, yes I think so, Google states it uses cookies.
- Client side fetch for request is a great suggestion too, and should help a lot !

Thanks a lot !
