### ISSUE TITLE
Transform XMLHttpRequest requests to fetch with cache

### ISSUE THREAD

**Issue by bacloud14** [bacloud14/WeatherVenue#37]
Apparently, `fetch` makes it easier to make asynchronous requests and handle responses better than with the older `XMLHttpRequest`. Other than that, I want to implement cached requests for all requests in `GMap.js`. Requests to be caches for say 5 hours. **This cache is only for our APIs, and surely not for Google APIs** (not allowed except some few conditions according to [this](https://developers.google.com/maps/documentation/places/web-service/policies))

To be cached:
https://github.com/bacloud14/WeatherVenue/blob/3da2f735ee2b5600120b14376c77eed02f69254f/src/js/GMap.js#L426
and 
https://github.com/bacloud14/WeatherVenue/blob/3da2f735ee2b5600120b14376c77eed02f69254f/src/js/GMap.js#L451

Nice implementation [here ](https://artandlogic.com/2016/10/go-fetch-2-javascript-fetch-api/)

**Comment by ME-ON1** [comment]
Axios can be used instead Fetch it works better with async too

**Comment by bacloud14** [comment]
yes, I think both are good, I will check some stable axios with cache fork out there.

**Comment by bacloud14** [comment]
resolved for `nearby` API, closing for now.
