### ISSUE TITLE
Rework all colors !!! (Color Theory involved)

### ISSUE THREAD

**Issue by bacloud14** [bacloud14/WeatherVenue#42]
I made colors out of my taste. Not good 👎 .
Dark mode using real black. Not good 👎 .
Bootstrap elements have very limited colors. Not good 👎 .
Staying harmonious with hue colors that reflect real temperature. Not good enough 😞 .
Having a look [at](https://www.webdesign-inspiration.com/web-designs/style/dark) then to weatherVenue. Not good 😥 .

Any designer 👨‍🎨 with a fine touch 🎨 to: 

1. Either propose a set of rules of colors 
Or
2. Implement it (or not, I can do the rest).

To consider:
Weather cards should keep their colors reflecting temperatures. 

Check:
Color theory applied in web, [here](https://webdesign.tutsplus.com/articles/an-introduction-to-color-theory-for-web-designers--webdesign-1437)
Color schemes [tutorial](https://hookagency.com/website-color-schemes/)

**Comment by grimxreaper** [comment]
Hi @bacloud14 ! I'm not a designer, but I love making things pretty and easier on the eyes. I could propose a set of colors and try my hand at this if that's alright?

**Comment by bacloud14** [comment]
I really appreciate this. It's yours 
Thanks 👍

**Comment by grimxreaper** [comment]
I followed your deployment guide and installed Redis but when I ran `npm install` to install dependencies and manually installed all the ones included in your slides [here](https://github.com/bacloud14/WeatherVenue/blob/master/CONTRIBUTING/CONTRIBUTING.pdf) under 'setup' (which you can see at the top of the image I attached). I received these errors that have to do with `gyp`, which I'm not sure what that is but I figured I would ask you if I need to install XCode for this project? Since that is partly what the errors point to. Happy to work on this if you could give me a hand with setting it up! Thank you.

<img width="859" alt="Screen Shot 2021-05-11 at 5 28 22 PM" src="https://user-images.githubusercontent.com/64915527/117887473-c3785a00-b27e-11eb-9424-7cfd9f656f53.png">

**Comment by bacloud14** [comment]
ok, you should not install anything manually after running `npm install`. As the tutorial was for how to build the whole project from scratch when you don't base your work on this repo.

In regards of the error, I do not know myself, however i think you are running on MacOS ?

I don't know about `node-pre-gyp` but I feel like it is demanded for your specific OS.

I can see sqlite3 demands `node-pre-gyp` 

Many people are having [this error ](https://github.com/mapbox/node-pre-gyp/issues/477) especially on Mac.

I suggest you first:

- run `npm install` with privileged rights (admin)
- downgrade Nodejs/npm (I am running `v12.16.3`) (I suggest `nvm` to be able to install multiple version, not to lose your current version).
- general install gyp ` npm install -g node-gyp`

let me know !!! thanks a lot !!!

**Comment by bacloud14** [comment]
-  I need to install XCode for this project?
not at all! feel free to use your best IDE. I use VSCode.

**Comment by bacloud14** [comment]
houray, `sqlite` is demanded by `offline-geocoder` which is not used anymore in this project and I forgot to clean it. You should remove it from `package.json` hoping sqlite is not used by another dependency there, and all should go right.

**Comment by grimxreaper** [comment]
- removed `offline-geocoder`
- ran the npm install again
- installed nvm and switched to v12.16.3
- installed gyp
All finished successfully!  

Before moving on I want to make sure I am using the right guide is [this ](https://github.com/bacloud14/WeatherVenue/discussions/33)the right one for deployment? So I will be picking up from Step 3: creating the .env file and getting all those API keys to fill in yes? What website do I get the "HONEYPOT_KEY" from? It isn't listed. Also, where would I find the REDIS_PORT?

Thanks for your help!!

**Comment by bacloud14** [comment]
Yes that guide is complete, but don't hesitate if anything goes wrong as there are some constraints.

Just run "Redis server" you have already installed separately and see logs in console. `6379` in mine, then pick it as a value that client (weathervenue) will connect to.

**[projecthoneypot](https://www.projecthoneypot.org/ )**  is one of the oldest, very effective databases against Spams. 

As we don't want bots coming to weathervenue.
You can have a free account from there, then go to `services\http blacklist` and create one.

**Comment by grimxreaper** [comment]
Hey there,

So for some reason, even after filling out all my keys in my .env file, I get the error **"Your port is undefined"** when I run `node server.js`. I installed [this npm package](https://www.npmjs.com/package/dotenv) thinking that perhaps it would help it find the PORT number if it wasn't accessing the .env file but it did not help. I'm pretty much stuck at this point since I've tried to debug using a number of things I read online in response to this error, including passing it the port from the command line, with a .env file, and installing dotenv from npm to read the .env file. 

Any help is appreciated, pictures attached to help. :)

<img width="542" alt="Screen Shot 2021-05-12 at 4 45 31 PM" src="https://user-images.githubusercontent.com/64915527/118042722-6ba32700-b342-11eb-9562-918df7830879.png">
<img width="386" alt="Screen Shot 2021-05-12 at 4 45 25 PM" src="https://user-images.githubusercontent.com/64915527/118042724-6ba32700-b342-11eb-9a8d-f70c38f825a9.png">

**Comment by bacloud14** [comment]
You should run `node index.js` or as in `package.json` `npm start`.

no, no, no...
the code getting variables (dotenv) is already defined everywhere in the project. **The file that dotenv relies on must be named .env**

so Yes, the error `Your port is undefined` is because the file was not properly created. just create a file named `.env` and only put text in it, no JS no require nothing else...

**Comment by bacloud14** [comment]
exactly `.env` must be in project root folder, with plain text in it like:

NODE_ENV=dev
PORT=####
REDIS_PORT=####
HONEYPOT_KEY=#######
OPENWEATHERMAP_API_KEY=********************************
GOOGLE_MAPS_API_KEY=#########-#######################
SENTRY_KEY=#####@####

dev and not development because that is the value defiled elsewhere in project like ` if (process.env.NODE_ENV === 'dev' ||  ...`

**Comment by grimxreaper** [comment]
Ah okay awesome, great! I did so, but then right before launch it gave me a Type error based on the code. I didn't want to alter the code at all before showing you this.

<img width="808" alt="Screen Shot 2021-05-13 at 10 47 02 AM" src="https://user-images.githubusercontent.com/64915527/118142845-c1c2a980-b3d8-11eb-82bb-83f23fdc7421.png">

**Comment by bacloud14** [comment]
Ok, great, that is another variable also defined on .env

I think it is required always but used only when env=prod please verify that environment variable is equal to "Dev" in your .env file. 

Anyway, I will check later and come back for exact answer.

**Comment by grimxreaper** [comment]
Yes, I changed it to Dev from dev and now I think I just need a Sentry key per this error. The Sentry key wasn't in your Deployment guide so I didn't know I needed it! But I just want to make sure, [this Sentry for Javascript](https://docs.sentry.io/api/projects/create-a-new-client-key/) is what I need to install? How do I then get the key? (Their docs mention this "The key's secret and public key are generated by the server.", but I'm not sure how to access that). Thanks! :)

<img width="396" alt="Screen Shot 2021-05-13 at 2 15 01 PM" src="https://user-images.githubusercontent.com/64915527/118168277-add97080-b3f5-11eb-8416-3f17a21c5549.png">

**Comment by bacloud14** [comment]
I'll verify all shortly

**Comment by bacloud14** [comment]
let's break it little by little,

we have this branch in code: 

https://github.com/bacloud14/WeatherVenue/blob/5fcb50bc54882ef87dcbb3024821e774c2c053df/index.js#L16

So Sentry is really needed only when `process.env.NODE_ENV !== 'dev'`. Then you don't really need neither an account nor a key,value in .env


Now about `pass`, this branch is the opposit:

https://github.com/bacloud14/WeatherVenue/blob/5fcb50bc54882ef87dcbb3024821e774c2c053df/index.js#L61

You need pass variable only when working on `dev` but you can override this one, as I was not sure about it's implementation (it is a security scheme to restrict some origins in case I give "my" Google Maps APIs keys to others.

Just change it to 

`if (process.env.NODE_ENV !== 'dev') {`

so it is not used anymore.



Lastly:

Go to `head.ejs` and remove all the meta tag
```
<meta http-equiv="Content-Security-Policy" 
   content="default-src 'self' cdn.jsdelivr.net; 
   script-src 'self' 'unsafe-inline' cdn.rtlcss.com code.jquery.com maps.googleapis.com unpkg.com www.google-analytics.com www.googletagmanager.com lh3.googleusercontent.com ajax.googleapis.com cdnjs.cloudflare.com polyfill.io stackpath.bootstrapcdn.com; 
   connect-src 'self' www.google-analytics.com; 
   img-src 'self' data: maps.gstatic.com *.googleapis.com *.ggpht openweathermap.org www.google-analytics.com maps.google.com lh3.googleusercontent.com; 
   style-src 'self' 'unsafe-inline' unpkg.com cdn.jsdelivr.net cdn.rtlcss.com stackpath.bootstrapcdn.com fonts.googleapis.com;
   font-src 'self' cdn.jsdelivr.net fonts.gstatic.com
   base-uri 'self';
   form-action 'self'">
```

This is something to do with security and really useful in prod environments. 

If anything goes wrong like the map not loading for example, or the pictures or the weather, then remove this line:

https://github.com/bacloud14/WeatherVenue/blob/5fcb50bc54882ef87dcbb3024821e774c2c053df/index.js#L30

Please let me know, and sorry for all these considerations.

**Comment by bacloud14** [comment]
NODE_ENV=dev and not NODE_ENV=Dev ! you changed it wrongly.

**Comment by grimxreaper** [comment]
Okay great that fixed that, but even with removing ` app.use(helmet({ contentSecurityPolicy: false })) `, it still doesn't render the map or images...Hmmm. And I don't see an error for it...

<img width="1664" alt="Screen Shot 2021-05-13 at 3 04 14 PM" src="https://user-images.githubusercontent.com/64915527/118174237-90f46b80-b3fc-11eb-977b-34c6cb4e39aa.png">

**Comment by bacloud14** [comment]
yes, I guess it's Google Maps APIs in your account are restricted to origins other than `localhost:3000`

I put in guide:

Enter the API you created, then you 'should' restrict accepted origins, this is a soft layer of security for your key in case it slip publicly. I suggest you restrict connections to something like localhost:3561 where 3561 will be the port of your Node.js server.

In your case, you should go into Google account, and check https://developers.google.com/maps/api-key-best-practices#restrict_apikey

You should allow `localhost:3000`,

**Comment by bacloud14** [comment]
like if you did not set a billing account (free 200$ quota per month, so very large for dev purposes)

**Comment by grimxreaper** [comment]
Finally everything is up and running! 😅🥳

**Comment by bacloud14** [comment]
Hooray, glad you learnt few things !

**Comment by grimxreaper** [comment]
Yes I'm glad! Before I change the colors, do you have a preference for one of these combinations?
[A](https://ibb.co/C7gBmLv)
[B](https://ibb.co/Wsmvns8)
[C](https://ibb.co/PxNqMtT)

**Comment by bacloud14** [comment]
I like these pallets really, hard to figure out, but I would go for A

**Comment by bacloud14** [comment]
Please, as always I suggest to add a link to your repo/portfolio in index page in footer. 
(if you want to 😄 )
It goes live on weathervenue.com 🥇

**Comment by bacloud14** [comment]
something I didn't mention, each modification on JS need to run `gulp version_dependencies`  before `npm start` again to see results.

**Comment by bacloud14** [comment]
Harmonious colors, easier on eyes thanks to @grimxreaper 
closing for now.
