### ISSUE TITLE
Add three.js weather scenes

### ISSUE THREAD

**Issue by bacloud14** [bacloud14/WeatherVenue#49]
I already added sun and rain scenes, check this https://github.com/bacloud14/WeatherVenue/discussions/48

Hopefully, we can add more 
Like this one
https://codepen.io/shubniggurath/pen/BVKgJK
And 
https://codepen.io/shubniggurath/pen/WgJZJo

**Comment by bacloud14** [comment]
Hello guys , is this rolling?
Thank you 😃

**Comment by japneetsingh035** [comment]
Hi @bacloud14, Yes! I am halfway through one scene will share the pr once done!

**Comment by bacloud14** [comment]
@japneetsingh035 a three.js scene is much better. 
I really appreciate your contribution but three.je is a must here. Thanns

**Comment by japneetsingh035** [comment]
Ohh! I am sorry, but I don't have an understanding of that code that was written and I can't copy & paste it as it is I assume. It's okay! I am happy to contribute even if it was not acceptable. Thank you for the opportunity.

**Comment by bacloud14** [comment]
I'm glad you learnt few things. Many thanks and keep an eye on issues if you want. 
I'm always available to help 
thanks
